import logging
import re
import yt_dlp
from utils import upperescape, find_best_match_index, YoutubeDLLogger, ytdl_hooks, ytdl_hooks_debug

logger = logging.getLogger('sonarr_youtubedl')

BGUTIL_SERVER = '/root/bgutil-ytdlp-pot-provider/server'
NODE_PATH = '/usr/local/bin/node'


def _pot_args():
    return {
        'extractor_args': {
            'youtubepot-bgutilscript': {
                'server_home': [BGUTIL_SERVER]
            }
        },
        'js_runtimes': {'node': {'path': NODE_PATH}},
        'remote_components': {'ejs:github'},
    }


def search(playlist_url, series_title, episode_title, playlistreverse, cookies=None, extra_args=None, debug=False):
    """Fetch playlist index and return the best matching video URL.

    Applies regex filter first, falls back to fuzzy match on full playlist
    if nothing matches — all in a single API call via extract_flat.
    """
    opts = {
        'ignoreerrors': True,
        'playlistreverse': playlistreverse,
        'extract_flat': True,
        'socket_timeout': 30,
        'quiet': not debug,
    }
    if debug:
        opts.update({'logger': YoutubeDLLogger(), 'progress_hooks': [ytdl_hooks]})
    if cookies:
        opts['cookiefile'] = cookies
    if extra_args:
        opts.update(extra_args)
    opts.update(_pot_args())

    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            result = ydl.extract_info(playlist_url, download=False)
    except Exception as e:
        logger.error(f"yt-dlp search error: {e}")
        return None

    if not result:
        return None

    if 'entries' not in result:
        url = result.get('webpage_url') or result.get('url')
        return url if url and url != playlist_url else None

    entries = [e for e in result['entries'] if e is not None]
    if not entries:
        return None

    regextitle = upperescape(episode_title)
    logger.debug(f"matchtitle regex: {regextitle}")

    filtered = [e for e in entries if re.search(regextitle, e.get('title', ''), re.IGNORECASE)]
    if filtered:
        logger.debug(f"Regex matched {len(filtered)} of {len(entries)} entries")
        candidates = filtered
    else:
        logger.debug(f"Regex matched nothing, using fuzzy on full playlist ({len(entries)} entries)")
        candidates = entries

    try:
        titles = [e.get('title', '').lower() for e in candidates]
        index = find_best_match_index(titles, f"{series_title} - {episode_title}".lower())
        url = candidates[index].get('webpage_url') or candidates[index].get('url')
        return url if url and url != playlist_url else None
    except Exception as e:
        logger.error(f"Error selecting best match: {e}")
        return None


def download(url, outtmpl, quality_format, cookies=None, extra_args=None, subtitles=None, debug=False):
    """Download a video to the given outtmpl path. Returns True on success."""
    opts = {
        'format': quality_format,
        'quiet': not debug,
        'outtmpl': outtmpl,
        'progress_hooks': [ytdl_hooks],
        'noplaylist': True,
        'socket_timeout': 30,
    }
    if debug:
        opts.update({'logger': YoutubeDLLogger(), 'progress_hooks': [ytdl_hooks_debug]})
    if cookies:
        opts['cookiefile'] = cookies
    if extra_args:
        opts.update(extra_args)
    if subtitles:
        opts.update({
            'writesubtitles': True,
            'writeautomaticsub': subtitles.get('autogenerated', False),
            'subtitleslangs': subtitles.get('languages', ['en']),
            'postprocessors': [
                {'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'},
                {'key': 'FFmpegEmbedSubtitle'},
            ],
        })
    opts.update(_pot_args())

    try:
        yt_dlp.YoutubeDL(opts).download([url])
        return True
    except Exception as e:
        logger.error(f"Download failed: {e}")
        return False