#!/usr/bin/env python3

import logging
import os
import re
import shutil
import sys
import time
from datetime import datetime

import schedule

import downloader
import staging_manager as staging
from sonarr_client import SonarrClient
from notifier import Notifier
from webhook import Webhook
from utils import escapetitle, checkconfig, offsethandler, setup_logging, calculate_backoff, is_rate_limit_error

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--debug', action='store_true')
parser.add_argument('--nologfile', action='store_true')

# Only parse args when run directly — not when imported by tests
if __name__ == '__main__' or 'pytest' not in sys.modules:
    args = parser.parse_args()
else:
    args = parser.parse_args([])

logger = setup_logging(not args.nologfile, True, args.debug)

date_format = "%Y-%m-%dT%H:%M:%SZ"
CONFIGFILE = os.environ['CONFIGPATH']
CONFIGPATH = CONFIGFILE.replace('config.yml', '')
SCANINTERVAL = 60
LOW_SCAN_INTERVAL_WARN = 10

last_checked: dict[int, datetime] = {}


class SonarrYTDL:

    def __init__(self):
        cfg = checkconfig()

        try:
            self._configure_logging(cfg)
            self._configure_sonarr(cfg)
            self._configure_ytdl(cfg)
            self._configure_paths(cfg)
            self._configure_staging()
            self._configure_rate_limiting(cfg)
        except SystemExit:
            raise
        except Exception as e:
            sys.exit(f"Configuration error: {e}")

        self.series_config = cfg.get('series', [])
        self.client = SonarrClient(self.base_url, self.api_version, self.api_key)

        self._check_sonarr_connection()

        res = self.client.get_naming_config()
        self._parse_naming(res)
        logger.debug(f"Number style: {self.number_style} folder: {self.season_format}")
        self.notifier = Notifier(cfg)
        self.webhook = Webhook(cfg)

    def _check_sonarr_connection(self):
        try:
            issues = self.client.get_health()
            if issues:
                for issue in issues:
                    level = issue.get('type', 'unknown')
                    message = issue.get('message', '')
                    logger.warning(f"Sonarr health {level}: {message}")
            else:
                logger.info("Sonarr connection OK")
        except Exception as e:
            sys.exit(f"Cannot connect to Sonarr at {self.base_url}: {e}")

    def _configure_logging(self, cfg):
        global SCANINTERVAL
        interval = int(cfg['sonarrytdl']['scan_interval'])
        if interval != SCANINTERVAL:
            SCANINTERVAL = interval
            logger.info(f"Scan interval: every {interval} minutes")
        else:
            logger.info(f"Scan interval: every {SCANINTERVAL} minutes (default)")

        if SCANINTERVAL < LOW_SCAN_INTERVAL_WARN:
            logger.warning(
                f"scan_interval is {SCANINTERVAL} minutes. This makes frequent requests "
                f"to Sonarr and YouTube. Consider using min_check_interval per series."
            )

        try:
            self.debug = cfg['sonarrytdl']['debug'] in ['true', 'True']
            if self.debug:
                logger.setLevel(logging.DEBUG)
                for h in logger.handlers:
                    h.setLevel(logging.DEBUG)
                logger.debug('DEBUGGING ENABLED')
        except (AttributeError, KeyError):
            self.debug = False

    def _configure_sonarr(self, cfg):
        sonarr = cfg['sonarr']
        scheme = 'https' if sonarr['ssl'].lower() == 'true' else 'http'
        basedir = f"/{sonarr['basedir']}" if sonarr.get('basedir') else ''
        api = 'api/v3' if sonarr.get('version', '').lower() == 'v4' else 'api'
        if api == 'api/v3':
            logger.debug('Sonarr api set to v4')

        self.base_url = f"{scheme}://{sonarr['host']}:{sonarr['port']}{basedir}"
        self.api_version = api
        self.api_key = sonarr['apikey']

    def _configure_ytdl(self, cfg):
        ytdl = cfg.get('ytdl', {})
        self.ytdl_format = ytdl.get('default_format', 'bestvideo+bestaudio/best')
        self.ytdl_subtitles = None

        if 'subtitles' in ytdl:
            self.ytdl_subtitles = {
                'languages': ytdl['subtitles'].get('languages', ['en']),
                'autogenerated': ytdl['subtitles'].get('autogenerated', False),
            }

        self.ytdl_extra_args = {}
        for key, value in (ytdl.get('extra_args') or {}).items():
            if value.lower() in ('true', 'false'):
                self.ytdl_extra_args[key] = value.lower() == 'true'
            else:
                try:
                    self.ytdl_extra_args[key] = int(value)
                except ValueError:
                    self.ytdl_extra_args[key] = value

    def _configure_paths(self, cfg):
        sonarr = cfg['sonarr']
        self.path = sonarr.get('path', '')
        self.localpath = sonarr.get('localpath', '/sonarr_root')
        self.staging_sonarr_path = sonarr.get('staging_path', '')

    def _configure_staging(self):
        if self.staging_sonarr_path and staging.is_available():
            self.use_staging = True
            staging.ensure()
            logger.info(f"Staging enabled: {self.staging_sonarr_path}")
        else:
            self.use_staging = False
            if self.staging_sonarr_path and not staging.is_available():
                logger.warning(
                    "staging_path is set but /staging is not available. "
                    "Falling back to direct library downloads."
                )
            else:
                logger.info("Staging not configured - downloads go directly to library")

    def _configure_rate_limiting(self, cfg):
        sonarrytdl = cfg['sonarrytdl']
        self.rate_limit_sleep = int(sonarrytdl.get('rate_limit_sleep', 900))
        self.backoff_multiplier = float(sonarrytdl.get('backoff_multiplier', 2.0))
        self.backoff_max = int(sonarrytdl.get('backoff_max', 3600))
        self.rate_limit_count = 0
        self.current_backoff = self.rate_limit_sleep
        logger.debug(
            f"Rate limiting: initial={self.rate_limit_sleep}s "
            f"multiplier={self.backoff_multiplier} max={self.backoff_max}s"
        )

    def _parse_naming(self, res):
        if 'seasonFolderFormat' not in res or (
            'numberStyle' not in res and 'standardEpisodeFormat' not in res
        ):
            self.season_format = 'Season {season:02d}'
            self.number_style = 'S{season:02d}E{episode:02d}'
            logger.debug("Using default Sonarr naming formats")
            return

        key = 'numberStyle' if 'numberStyle' in res else 'standardEpisodeFormat'
        for fmt_key in ['seasonFolderFormat', key]:
            original = self._extract_number_style(res[fmt_key]) if fmt_key == 'standardEpisodeFormat' else res[fmt_key]
            if ':' in original:
                start = original.find(':')
                end = original.find('}')
                length = end - start - 1
                original = original.replace(original[start:end], f":0{length}d")
                res[fmt_key] = original

        self.season_format = res['seasonFolderFormat']
        self.number_style = res[key]

    def _extract_number_style(self, text):
        pattern = re.compile(r'\s?[^.\s]*\{season:\d+\}\s?[^\s]*\{episode:\d+\}')
        matches = pattern.findall(text)
        return ''.join(m.strip() for m in matches) if matches else 'S{season:00}E{episode:00}'

    def _quality_format(self, profile_id):
        trans = {480: 640, 720: 1280, 1080: 1920, 2160: 3840}
        res = self.client.get_quality_profile(profile_id)
        res_max = max(
            (q['quality']['resolution'] for q in res['items'] if q['allowed'] and 'quality' in q),
            default=1080
        )
        width = trans.get(res_max, 1920)
        return f"bestvideo[width<={width}]+bestaudio/best[width<={width}]"

    def _series_path(self, ser):
        if self.path:
            return ser['path'].replace(self.path, self.localpath)
        return os.path.join(self.localpath, ser['title'])

    def _library_path(self, ser, eps):
        season_dir = self.season_format.format(season=eps['seasonNumber'])
        number = self.number_style.format(season=eps['seasonNumber'], episode=eps['episodeNumber'])
        clean_title = eps['title'].replace('/', '')
        return os.path.join(
            self._series_path(ser),
            season_dir,
            f"{ser['title']} - {number} - {clean_title} WEBDL.%(ext)s"
        )

    def _library_file_exists(self, ser, eps):
        number = self.number_style.format(season=eps['seasonNumber'], episode=eps['episodeNumber'])
        season_dir = self.season_format.format(season=eps['seasonNumber'])
        season_path = os.path.join(self._series_path(ser), season_dir)
        if not os.path.isdir(season_path):
            return False
        return any(number in f for f in os.listdir(season_path))

    def filterseries(self):
        all_series = self.client.get_series()
        matched = []
        for ser in all_series:
            cfg = next((w for w in self.series_config if w['title'] == ser['title']), None)
            if not cfg:
                continue

            ser['playlistreverse'] = cfg.get('playlistreverse', 'True') != 'False'
            ser['url'] = cfg['url']
            ser['min_check_interval'] = int(cfg.get('min_check_interval', 0))
            ser['subtitles'] = self.ytdl_subtitles
            ser['cookies_file'] = None

            if 'cookies_file' in cfg:
                path = os.path.abspath(CONFIGPATH + cfg['cookies_file'])
                if os.path.exists(path):
                    ser['cookies_file'] = path
                else:
                    logger.warning(f"Cookie file not found: {path}")

            if 'format' in cfg:
                ser['format'] = cfg['format']

            if 'subtitles' in cfg:
                ser['subtitles'] = {
                    'languages': cfg['subtitles'].get('languages', ['en']),
                    'autogenerated': cfg['subtitles'].get('autogenerated', False),
                }

            if 'regex' in cfg:
                if 'sonarr' in cfg['regex']:
                    ser['sonarr_regex'] = cfg['regex']['sonarr']
                if 'site' in cfg['regex']:
                    ser['site_regex'] = cfg['regex']['site']

            if 'offset' in cfg:
                ser['offset'] = cfg['offset']

            if 'extra_args' in cfg:
                parsed = {}
                for key, value in cfg['extra_args'].items():
                    if str(value).lower() in ('true', 'false'):
                        parsed[key] = str(value).lower() == 'true'
                    else:
                        try:
                            parsed[key] = int(value)
                        except (ValueError, TypeError):
                            parsed[key] = value
                ser['extra_args'] = parsed

            if not ser['monitored']:
                logger.warning(f"{ser['title']} is not monitored")

            matched.append(ser)
        return matched

    def get_missing_episodes(self, series):
        now = datetime.now()
        needed = []
        quality_ids = set()

        for ser in series[:]:
            episodes = self.client.get_episodes(ser['id'])
            wanted = []
            for eps in episodes:
                if not eps['monitored'] or eps['hasFile']:
                    continue
                eps_date = now
                if 'airDateUtc' in eps:
                    eps_date = datetime.strptime(eps['airDateUtc'], date_format)
                    if 'offset' in ser:
                        eps_date = offsethandler(eps_date, ser['offset'])
                if eps_date > now:
                    continue
                if 'sonarr_regex' in ser:
                    eps['title'] = re.sub(
                        ser['sonarr_regex']['match'],
                        ser['sonarr_regex']['replace'],
                        eps['title']
                    )
                wanted.append(eps)
                quality_ids.add(ser['qualityProfileId'])

            if not wanted:
                logger.info(f"{ser['title']}: no episodes needed")
                series.remove(ser)
            else:
                needed.extend(wanted)
                logger.info(f"{ser['title']}: {len(wanted)} episode(s) missing")
                for i, e in enumerate(wanted):
                    logger.info(f"  {i + 1}: {ser['title']} - {e['title']}")

        self.quality_map = {qid: self._quality_format(qid) for qid in quality_ids}
        return needed

    def _download_episode(self, ser, eps):
        number = self.number_style.format(season=eps['seasonNumber'], episode=eps['episodeNumber'])

        # Resume interrupted staging download
        if self.use_staging:
            existing = staging.find_file(ser['title'], number)
            if existing:
                logger.info(f"Resuming staged file: {os.path.basename(existing)}")
                if not staging.notify_sonarr(self.client, existing, self.staging_sonarr_path):
                    staging._fallback(self.client, existing, self.season_format, self.path, self.localpath)
                return True

        # Skip if library file exists but Sonarr doesn't know about it
        if self._library_file_exists(ser, eps):
            logger.info(f"Library file exists for: {eps['title']} - rescanning")
            self.client.refresh(ser['id'])
            self.client.rescan(ser['id'])
            return True

        # Search YouTube
        episode_title = eps['title']
        if 'site_regex' in ser:
            episode_title = re.sub(ser['site_regex']['match'], ser['site_regex']['replace'], episode_title)

        extra_args = {**self.ytdl_extra_args, **ser.get('extra_args', {})}

        url = downloader.search(
            playlist_url=ser['url'],
            series_title=ser['title'],
            episode_title=episode_title,
            playlistreverse=ser['playlistreverse'],
            cookies=ser.get('cookies_file'),
            extra_args=extra_args or None,
            debug=self.debug
        )

        if not url:
            return False

        logger.info(f"Downloading: {eps['title']}")

        quality = ser.get('format') or self.quality_map.get(ser['qualityProfileId'], self.ytdl_format)
        subtitles = ser.get('subtitles')

        if self.use_staging:
            outtmpl = staging.staging_path(ser['title'], number)
        else:
            outtmpl = self._library_path(ser, eps)

        self.notifier.notify_download_start(ser['title'], eps['title'])
        self.webhook.notify_download_start(ser['title'], number, eps['title'])
        try:
            success = downloader.download(
                url=url,
                outtmpl=outtmpl,
                quality_format=quality,
                cookies=ser.get('cookies_file'),
                extra_args=extra_args or None,
                subtitles=subtitles,
                debug=self.debug
            )
        except Exception as e:
            error_msg = str(e)
            if is_rate_limit_error(error_msg):
                self.rate_limit_count += 1
                self.current_backoff = calculate_backoff(
                    self.rate_limit_count,
                    self.rate_limit_sleep,
                    self.backoff_multiplier,
                    self.backoff_max
                )
                if self.rate_limit_count > 1:
                    logger.warning(
                        f"Rate limited (attempt {self.rate_limit_count}), "
                        f"backing off {self.current_backoff}s "
                        f"({self.current_backoff // 60}m {self.current_backoff % 60}s)"
                    )
                else:
                    logger.warning(f"Rate limited, sleeping {self.current_backoff}s")
                time.sleep(self.current_backoff)
            else:
                logger.error(f"Download error: {eps['title']} - {e}")
            return False

        if not success:
            return False

        self.notifier.notify_download_complete(ser['title'], eps['title'])
        self.webhook.notify_download_complete(ser['title'], number, eps['title'])

        # Reset backoff on successful download
        if self.rate_limit_count > 0:
            logger.info("Rate limit recovered - resetting backoff")
            self.rate_limit_count = 0
            self.current_backoff = self.rate_limit_sleep

        if self.use_staging:
            staged = staging.find_file(ser['title'], number)
            if not staged:
                logger.error(f"Staged file not found after download: {eps['title']}")
                return False
            if not staging.notify_sonarr(self.client, staged, self.staging_sonarr_path):
                staging._fallback(self.client, staged, self.season_format, self.path, self.localpath)
        else:
            logger.info(f"Rescanning {ser['title']} in Sonarr")
            time.sleep(15)
            self.client.refresh(ser['id'])
            self.client.rescan(ser['id'])

        return True

    def download(self, series, episodes):
        if not series:
            logger.info("Nothing to process")
            return

        if self.use_staging:
            staging.clean(self.client, self.season_format, self.path, self.localpath)

        logger.info("Processing wanted downloads")

        for ser in series:
            logger.info(f"  {ser['title']}:")

            now = datetime.now()
            min_interval = ser.get('min_check_interval', 0)
            last = last_checked.get(ser['id'])
            if last and min_interval:
                elapsed = (now - last).total_seconds() / 60
                if elapsed < min_interval:
                    logger.debug(f"{ser['title']}: skipping, checked {elapsed:.0f}m ago")
                    continue

            last_checked[ser['id']] = now

            for e, eps in enumerate(episodes):
                if ser['id'] != eps['seriesId']:
                    continue
                downloaded = self._download_episode(ser, eps)
                status = "Downloaded" if downloaded else "Missing"
                logger.info(f"    {e + 1}: {status} - {eps['title']}")


def main():
    client = SonarrYTDL()
    series = client.filterseries()
    episodes = client.get_missing_episodes(series)
    client.download(series, episodes)
    logger.info("Waiting...")


if __name__ == "__main__":
    logger.info("Initial run")
    main()
    schedule.every(int(SCANINTERVAL)).minutes.do(main)
    while True:
        schedule.run_pending()
        time.sleep(1)